# Generated by Django 3.1.5 on 2021-01-05 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('linguas', '0002_lingua_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Termo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('lingua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='linguas.lingua')),
            ],
        ),
    ]
