# Generated by Django 3.1.5 on 2021-01-05 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linguas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lingua',
            name='descricao',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
